const instruments = [
  {
    fileName: "piano",
    fade: 0.1
  }, {
    fileName: "harpsichord",
    fade: 0.2
  }, {
    fileName: "rhodes",
    fade: 0.1
  }, {
    fileName: "harp",
    fade: 0.2
  }, {
    fileName: "choir",
    fade: 0.5
  }, {
    fileName: "strings",
    fade: 0.9
  }, {
    fileName: "sawtooth",
    fade: 0.2
  }, {
    fileName: "gayageum",
    fade: 1
  }, {
    fileName: "qanun",
    fade: 1
  }, {
    fileName: "organ",
    fade: 0.1
  }, {
    fileName: "organleslie",
    fade: 0.1
  }, {
    fileName: "marimba",
    fade: 0.1
  }, {
    fileName: "musicbox",
    fade: 0.1
  }, {
    fileName: "WMRI3LST",
    fade: 0.1
  }, {
    fileName: "WMRI5LST",
    fade: 0.1
  }, {
    fileName: "WMRI5Lpike",
    fade: 0.1
  }, {
    fileName: "WMRI7LST",
    fade: 0.1
  }, {
    fileName: "WMRI11LST",
    fade: 0.1
  }, {
    fileName: "WMRI13LST",
    fade: 0.1
  }, {
    fileName: "WMRInLST",
    fade: 0.1
  }, {
    fileName: "WMRIByzantineST",
    fade: 0.1
  }, {
    fileName: "WMRI-in6-har7-",
    fade: 0.1
  }, {
    fileName: "WMRI-in7-har6-",
    fade: 0.1
  }
];

export default instruments;
